### ISSUE TITLE
1.5.3Dev cannot display the settings of add-ons in the settings panel

### ISSUE THREAD

**Issue by cary-rowen** [grisov/Unmute#24]
As the title says, I tested 2020.4 and the latest Alpha 22012.
The following is the test log:
[NVDA_Log_UnMute.txt](https://github.com/grisov/Unmute/files/6163915/NVDA_Log_UnMute.txt)

**Comment by grisov** [comment]
Hi Cary,  
Thank you for the feedback!  

Judging by the contents of the attached log, most likely there were problems when installing the add-on and the third-party module **psutil** was not fully installed.  
Could you try to reinstall the latest version of the add-on?  

Also you can check for existing the following files in the following directory:  
"nvda\addons\unmute\globalPlugins\unmute\psutil\"  

* "_psutil_windows.cp37-win32.pyd"  # for NVDA 2020.4 or older
* "_psutil_windows.cp38-win32.pyd"  # for alpha snapshots of NVDA 2021

One of the users has encountered this problem before and reinstalling the add-on helped.  
The fact is that when uninstalling an older version of the add-on, pyd-files are often occupied by another process and NVDA cannot delete them completely. Because of this, there are sometimes errors when installing a new copy of the add-on.

I also refactored the Settings Panel ca5d2792da528483bf2f98400d831c49407 .  

Good luck!

**Comment by cary-rowen** [comment]
OK, according to your instructions, I found out that these two files are indeed missing:

* unmute\globalPlugins\unmute\psutil
    - _psutil_windows.cp38-win32.pyd
    - _psutil_windows.cp37-win32.pyd

I cloned the following repository but did not find these two files. Is it possible that you have overlooked them?

``` git clone git@github.com:grisov/Unmute.git ```

**Comment by grisov** [comment]
Oh, sorry, Cary... It was my mistake...  

GitHub ignored PYD-files due to a template error in the ".gitignore" file.  
This has been fixed here 41edd9827 .  
Please try again.  

Thanks for letting me know about this error.

**Comment by cary-rowen** [comment]
you are welcome.

There is no problem now, I updated the simplified Chinese translation.

Have a nice weekend!
