### ISSUE TITLE
When a profile configuration is active, add-ons settings won't be applied at startup

### ISSUE THREAD

**Issue by nvdaes** [grisov/Unmute#27]
After reading the source code I figured that this issue may happens, and I have tested it to confirm:

STR:

1. Activate a configuration profile
2. Uncheck the Play sound when audio has been successfully turned on checkbox
3. Decrease the volume to ensure that the add-on will work when NVDA is restarted
4. Restart NVDA

Expected: the add-on shouldn't allow to change settings if they won't be applicable, since if maybe confusing.

If you can confirm this issue, imo the add-on should be fixed before posting it on the website since this is a bug that may affect user experience.

cc: @josephsl

**Comment by grisov** [comment]
Hi Noelia,  

Yes, you are right, I just reproduced this incorrect add-on behavior.  
Unfortunately, I didn't find standard solutions to this situation in other add-ons.  

My decision is based on displaying a warning and exiting the settings without saving the configuration 89c6371ba5b41500958ee01 .  

Please could you review this changes?

**Comment by nvdaes** [comment]
Thanks so much! I'll review changes this weekend. Hope this superuseful add-on can be posted on the website! I'm also interested.

**Comment by grisov** [comment]
I'm very grateful to you for such a kind words!  

Today I made some small changes.
The main changes related to this issue are in the file "settings.py" -> method `UnmuteSettingsPanel.onSave()`.  

Have a nice week and - keep in touch!

**Comment by nvdaes** [comment]
Hello Oleksandr, I've reviewed the mentioned changes and they are good. Anyway, please take a look to this message related to other add-on, containing code that doesn't require to display error messages.
What do you think? Maybe applicable to this add-on¿

https://nvda-addons.groups.io/g/nvda-addons/message/15140

Have a nice weekend!

**Comment by grisov** [comment]
Hello Noelia,  

Thanks for the tip in resolving this issue!  
I updated the onSave() method 709698c16fafb76f33a486c .  

Cheers.

**Comment by nvdaes** [comment]
Great! I've reviewed the code and tomorrow I'll test it and, if you want, can create a PR in addonFiles repo.
Nice work!

**Comment by nvdaes** [comment]
Hi again: this would work perfectly if you make a small change. Seems you have used ADDON_NAME in the new onSave method. You have to use _addonName.

I have tested it fixing this and it works as expected, so that settings are always saved in the base configuration, even when a profile is being edited.

Also, I'd like to remark an add-on not currently maintained, but for historical reasons you may know it. It was not posted on the website. I think that the documentation format was difficult to be included in the translation system:

https://github.com/Robert-J-H/SharedComputer

I'm mentioned as an author, but my contribution was supersmall. I created an add-on requested in a spanish list to ensure that the numlock was not active to be used by NVDA, Robert added the main part of the add-on and I preferred him to be considered the main author and maintainer. He is a member of the add-ons mailing list. Just in case this was not mentioned before.

Furthermore, should you make a note about license of third party components?

Also, I noted that you used a list instead of a tuple to check if a value is included, for example, if value in [a, b] instead of (a, b). Not sure if it's right, though it's not part of basic review. Also, you may prefer to use the .name property of the add-on to get the addon name, instead of using ["manifest"]["name"].

And finishing my comments, you may want to read the add-on guidelines originally created by Mesar Hameed, the creator of the translation system used by add-ons and NVDA (now NV Access is in charge). These guidelines try to provide guidance about documentation, considering that it was to be translated, so it's not so verbose. They are optional:

https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/guideLines

See you soon!

**Comment by grisov** [comment]
Yes, I used "_addonName" before.  

But recently I optimized this part of the "__init__.py" code a bit and changed the name of the variables, because in essence they have to be constants:  

```
ADDON_NAME: str = addonHandler.getCodeAddon().manifest['name']  
ADDON_SUMMARY: str = addonHandler.getCodeAddon().manifest['summary']  
```

Thank you for the link to the SharedComputer add-on. Unfortunately, I didn't know about it before. It performs very similar functions.  
I studied the source code of this add-on. In terms of interaction with the Windows Core Audio API, it also uses code snippets from a third-party module [PyCaw](https://github.com/AndreMiras/pycaw/).  

The PyCaw module is distributed under the MIT license. Could this be a problem?  
Another third-party module [psutil](https://github.com/giampaolo/psutil) is licensed as BSD-3. This module is also used in some other NVDA add-ons.  
I'm not a big expert of licensing and all sorts of legal things. But, as far as I know, the mentioned MIT and BSD-3 licenses provide for free distribution of the software product and they are the equivalent of GPL compatible licenses.  
Undoubtedly, I will mention these third-party components in the add-on documentation.  

Relatively using a list instead of a tuple. In this matter, I completely agree with you and have already corrected this shortcoming 4a6cb52932a77 .  

Thank you for the add-on guidelines by Mesar Hameed. I will definitely study these step-by-step instructions.

**Comment by nvdaes** [comment]
Hi Oleksandr, thank you so much. As you mentioned, BSD and MIT are compatible licenses, as far as I know, though I'm not an expert ☺

I commented this just in case it should be mentioned. I agree with you: I prefer constants for add-on name and summary. Also, you may use:

ADDON_NAME: str = addonHandler.getCodeAddon().name

Just if you want. I'll review this later.

Cheers

**Comment by grisov** [comment]
oh, thank you for the hint ;)

Now the name property is used instead extracting a name from the manifest ff1b86b084b28c .  

A section on third-party components used in the add-on has also been added to the ReadMe 62833bc8ca77 .  

If you don't mind - may I create PR?

**Comment by nvdaes** [comment]
I"ll review this, and if all is ok, may approve de Pr or @josephsl will do. Both can do it since both reviewed this add-on. Thanks

**Comment by grisov** [comment]
ok, thank you very much!  

Have a nice day!

**Comment by nvdaes** [comment]
Fixed. Thanks!
